"""add-phone-number

Revision ID: 5d534713cb79
Revises: bf0071cd076c
Create Date: 2022-01-14 13:38:18.085290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d534713cb79'
down_revision = 'bf0071cd076c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
